var vue = new Vue({
    el: "#app",
    data: {
        users: [
            {id: 1, nickname: "dafei", headImgUrl: "/images/default.jpg"},
            {id: 2, nickname: "dafei", headImgUrl: "/images/default.jpg"},
            {id: 3, nickname: "dafei", headImgUrl: "/images/default.jpg"},
            {id: 4, nickname: "dafei", headImgUrl: "/images/default.jpg"},
            {id: 5, nickname: "dafei", headImgUrl: "/images/default.jpg"},
            {id: 5, nickname: "dafei", headImgUrl: "/images/default.jpg"},
            {id: 5, nickname: "dafei", headImgUrl: "/images/default.jpg"},
            {id: 5, nickname: "dafei", headImgUrl: "/images/default.jpg"},
            {id: 6, nickname: "dafei", headImgUrl: "/images/default.jpg"},
            {id: 6, nickname: "dafei", headImgUrl: "/images/default.jpg"},
            {id: 6, nickname: "dafei", headImgUrl: "/images/default.jpg"},
            {id: 6, nickname: "dafei", headImgUrl: "/images/default.jpg"},
            {id: 6, nickname: "dafei", headImgUrl: "/images/default.jpg"},
            {id: 6, nickname: "dafei", headImgUrl: "/images/default.jpg"},
            {id: 6, nickname: "dafei", headImgUrl: "/images/default.jpg"},
            {id: 6, nickname: "dafei", headImgUrl: "/images/default.jpg"},
            {id: 6, nickname: "dafei", headImgUrl: "/images/default.jpg"},
            {id: 6, nickname: "dafei", headImgUrl: "/images/default.jpg"},
            {id: 6, nickname: "dafei", headImgUrl: "/images/default.jpg"},
            {id: 6, nickname: "dafei", headImgUrl: "/images/default.jpg"},
            {id: 6, nickname: "dafei", headImgUrl: "/images/default.jpg"},
            {id: 6, nickname: "dafei", headImgUrl: "/images/default.jpg"},
            {id: 6, nickname: "dafei", headImgUrl: "/images/default.jpg"},
            {id: 6, nickname: "dafei", headImgUrl: "/images/default.jpg"},
            {id: 6, nickname: "dafei", headImgUrl: "/images/default.jpg"},
            {id: 6, nickname: "dafei", headImgUrl: "/images/default.jpg"},
            {id: 6, nickname: "dafei", headImgUrl: "/images/default.jpg"},
            {id: 6, nickname: "dafei", headImgUrl: "/images/default.jpg"},
            {id: 6, nickname: "dafei", headImgUrl: "/images/default.jpg"},
            {id: 6, nickname: "dafei", headImgUrl: "/images/default.jpg"},
            {id: 6, nickname: "dafei", headImgUrl: "/images/default.jpg"},
            {id: 6, nickname: "dafei", headImgUrl: "/images/default.jpg"},
            {id: 6, nickname: "dafei", headImgUrl: "/images/default.jpg"},
            {id: 6, nickname: "dafei", headImgUrl: "/images/default.jpg"},
            {id: 6, nickname: "dafei", headImgUrl: "/images/default.jpg"},
            {id: 6, nickname: "dafei", headImgUrl: "/images/default.jpg"},
            {id: 6, nickname: "dafei", headImgUrl: "/images/default.jpg"},
            {id: 6, nickname: "dafei", headImgUrl: "/images/default.jpg"},
            {id: 6, nickname: "dafei", headImgUrl: "/images/default.jpg"},
            {id: 6, nickname: "dafei", headImgUrl: "/images/default.jpg"},
            {id: 6, nickname: "dafei", headImgUrl: "/images/default.jpg"},
            {id: 6, nickname: "dafei", headImgUrl: "/images/default.jpg"},
            {id: 6, nickname: "dafei", headImgUrl: "/images/default.jpg"},
            {id: 6, nickname: "dafei", headImgUrl: "/images/default.jpg"},
            {id: 6, nickname: "dafei", headImgUrl: "/images/default.jpg"},
            {id: 6, nickname: "dafei", headImgUrl: "/images/default.jpg"},
            {id: 6, nickname: "dafei", headImgUrl: "/images/default.jpg"},
            {id: 6, nickname: "dafei", headImgUrl: "/images/default.jpg"},
            {id: 6, nickname: "dafei", headImgUrl: "/images/default.jpg"},
            {id: 6, nickname: "dafei", headImgUrl: "/images/default.jpg"},
            {id: 6, nickname: "dafei", headImgUrl: "/images/default.jpg"},
            {id: 6, nickname: "dafei", headImgUrl: "/images/default.jpg"},
            {id: 6, nickname: "dafei", headImgUrl: "/images/default.jpg"},
            {id: 6, nickname: "dafei", headImgUrl: "/images/default.jpg"},
            {id: 6, nickname: "dafei", headImgUrl: "/images/default.jpg"},
            {id: 6, nickname: "dafei", headImgUrl: "/images/default.jpg"},
            {id: 6, nickname: "dafei", headImgUrl: "/images/default.jpg"},
            {id: 6, nickname: "dafei", headImgUrl: "/images/default.jpg"},
            {id: 6, nickname: "dafei", headImgUrl: "/images/default.jpg"},
            {id: 6, nickname: "dafei", headImgUrl: "/images/default.jpg"},
            {id: 6, nickname: "dafei", headImgUrl: "/images/default.jpg"},
            {id: 6, nickname: "dafei", headImgUrl: "/images/default.jpg"},
            {id: 7, nickname: "dafei", headImgUrl: "/images/default.jpg"},
            {id: 8, nickname: "dafei", headImgUrl: "/images/default.jpg"}
        ]
    },
    methods: {},
    filters: {},
    mounted: function () {
        var param = getParams();
    }
});

